### ISSUE TITLE
cross sample analysis

### ISSUE THREAD

**Issue by Mangosteen24** [michael-nakai/isopod#2]
Hi Michael. Thanks for developing this useful tool! I want to try it out on my single-cell long-read data and have a few questions:

1. Would the calculation of DTU be influenced by a large number of cell numbers bias in different cell type groups?
2. If I want to try it on several patients in different groups and then analyze cell type-specific DTU between patients in different groups (like 10 healthy and 10 diseased), would you recommend separating the isoform matrix by cell types, merge the same cell type matrices from different patients, and then use Isopod for the DTU analysis?

Moreover, could you suggest how to solve this error?
```
permutation_results_all_groups <- get_permutation_pvals(iso_matrice,
                                      cell_groups,
                                      transcript_id_colname = 'ensembl_transcript_id',
                                      gene_id_colname = 'gene_id',
                                      cell_labels_colname = 'cell_group',
                                      run_on_all_groups = TRUE,
                                      do_gene_level_comparisons = TRUE)
Error in rowSums(a) : 'x' must be an array of at least two dimensions
```

**Comment by michael-nakai** [comment]
Hi @Mangosteen24, let me look into the issue, but in the meanwhile:

1. From our testing, Isopod is quite resistant to harsh cell group ratios. We've tested up to a 10:1 group size ratio and haven't found a significant increase in the false discovery rate, so you should be alright. That being said, the more balanced (and the more absolute cells you have), the better.

2. It may not be advisable to combine cells between patients, since their expression would be in context of each patient. Instead, I'd separate by cell type and run Isopod on each patient's data, check each's results, and see if you find common significant  isoforms/genes between each. In your case, an approach may be to compare all the healthy samples first, then all the diseased, and see if you find differences in significant isoforms/genes between them.

While I'm looking into the error, I'd recommend running the provided functions individually. So start with [filter_counts_table](https://github.com/michael-nakai/isopod/blob/main/R/filter_counts_table.R), then get the p-values with [get_permutation_pvals](https://github.com/michael-nakai/isopod/blob/main/R/get_permutation_pvals.R). Let me know if that works for you!

**Comment by michael-nakai** [comment]
I'm not able to replicate the error on my side, could you please paste the output of `str(iso_matrice)` and `str(cell_groups)` here?

**Comment by michael-nakai** [comment]
Closing the issue, please reopen if you're still experiencing problems.
